name: Build and Release

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x.x' # Replace with your .NET version

    - name: Update Project Version
      run: |
        pwsh ./Zatca.EGS/UpdateVersion.ps1 # Path to your PowerShell script

    - name: Build and Publish for Multiple Runtimes
      run: |
        # Build and publish for each target runtime
        targets=("linux-x64" "win-x64" "osx-x64")
        for target in "${targets[@]}"; do
            dotnet publish -c Release -r $target --self-contained false -o ./publish/$target
        done

    - name: Create ZIP Files
      run: |
        cd publish/linux-x64
        zip -r ZatcaEGS-linux-x64.zip .
        cd ../win-x64
        zip -r ZatcaEGS-win-x64.zip .
        cd ../osx-x64
        zip -r ZatcaEGS-osx-x64.zip .
        cd ..

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release for ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Linux Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish/linux-x64/ZatcaEGS-linux-x64.zip
        asset_name: ZatcaEGS-linux-x64.zip
        asset_content_type: application/zip

    - name: Upload Windows Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish/win-x64/ZatcaEGS-win-x64.zip
        asset_name: ZatcaEGS-win-x64.zip
        asset_content_type: application/zip

    - name: Upload macOS Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish/osx-x64/ZatcaEGS-osx-x64.zip
        asset_name: ZatcaEGS-osx-x64.zip
        asset_content_type: application/zip
